name: 'metal'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  project:
    env:
      METAL_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    # TODO(displague) PROJECT_ID should also be globalized
    steps:
    - run: find ${{ runner.temp }}/.. -ls 
    - id: metal-project
      uses: displague/metal-project-action@v0.9.0
    - name: Use the Project ID (display it)
      run: |
        echo Equinix Metal Project "$PROJECT_NAME" has ID "$PROJECT_ID"
      env:
        PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
        PROJECT_NAME: ${{ steps.metal-project.outputs.projectName }}
    - name: Project Delete
      uses: displague/metal-sweeper-action@v0.3.0
      env:
        METAL_PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
